### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by kdambekalns** [vivomedia-de/fusion-cachevisualisation#1]
Very helpful tool! But I needed to run the "enabling JS" manually after the page loaded. Because I get this in the JS console during page load:

```
cachevisualisation.js:1 Uncaught ReferenceError: $ is not defined
```

This requirement should at least be mentioned in the docs…

**Comment by dlubitz** [comment]
Thanks @kdambekalns. Is fixed in 0.3 for most cases e.g demo site. Had to move the JS to the end of body.
I will add a note for the requirement of jQuery.
